In [2]:
import tensorflow as tf
import numpy as np

In [5]:
dataset = tf.data.Dataset.from_tensor_slices(np.array(range(10)))
dataset = dataset.shuffle(5).repeat(3).batch(4)
for i, ele in enumerate(dataset):
    print(i, ele)

0 tf.Tensor([1 4 2 5], shape=(4,), dtype=int64)
1 tf.Tensor([0 6 9 3], shape=(4,), dtype=int64)
2 tf.Tensor([7 8 1 3], shape=(4,), dtype=int64)
3 tf.Tensor([5 2 0 6], shape=(4,), dtype=int64)
4 tf.Tensor([4 8 7 9], shape=(4,), dtype=int64)
5 tf.Tensor([4 5 0 1], shape=(4,), dtype=int64)
6 tf.Tensor([6 2 7 3], shape=(4,), dtype=int64)
7 tf.Tensor([8 9], shape=(2,), dtype=int64)


In [6]:
# shuffle first, then repeat, the whole data will be saved in one epoch.
dataset = tf.data.Dataset.from_tensor_slices(np.array(range(10)))
dataset = dataset.repeat(3).shuffle(5).batch(4)
for i, ele in enumerate(dataset):
    print(i, ele)

0 tf.Tensor([0 3 2 5], shape=(4,), dtype=int64)
1 tf.Tensor([7 1 6 8], shape=(4,), dtype=int64)
2 tf.Tensor([0 9 4 5], shape=(4,), dtype=int64)
3 tf.Tensor([6 4 2 8], shape=(4,), dtype=int64)
4 tf.Tensor([9 0 1 3], shape=(4,), dtype=int64)
5 tf.Tensor([4 2 5 7], shape=(4,), dtype=int64)
6 tf.Tensor([7 1 8 9], shape=(4,), dtype=int64)
7 tf.Tensor([3 6], shape=(2,), dtype=int64)


In [7]:
dataset = tf.data.Dataset.from_tensor_slices(np.array(range(10)))
dataset = dataset.shuffle(5).batch(4).repeat(3)
for i, ele in enumerate(dataset):
    print(i, ele)

0 tf.Tensor([2 4 6 5], shape=(4,), dtype=int64)
1 tf.Tensor([8 1 3 7], shape=(4,), dtype=int64)
2 tf.Tensor([9 0], shape=(2,), dtype=int64)
3 tf.Tensor([1 3 2 4], shape=(4,), dtype=int64)
4 tf.Tensor([6 5 8 0], shape=(4,), dtype=int64)
5 tf.Tensor([7 9], shape=(2,), dtype=int64)
6 tf.Tensor([2 1 5 3], shape=(4,), dtype=int64)
7 tf.Tensor([6 9 7 8], shape=(4,), dtype=int64)
8 tf.Tensor([0 4], shape=(2,), dtype=int64)
